from checkers.game_constants import ROWS, COLUMNS

FPS = 60
WINDOW_WIDTH, WINDOW_HEIGHT = 1000, 1000
ICON_PATH = 'graphics/img/checkers_logo.png'
WINDOW_CAPTION = 'Polish Checkers by Paweł Mędyk'

SQUARE_WIDTH = WINDOW_WIDTH//COLUMNS
SQUARE_HEIGHT = WINDOW_HEIGHT//ROWS

CROWN_IMG_PATH = 'graphics/img/crown.png'
PIECE_DIAMETER_TO_SQUARE_SIZE_RATIO = 3/4
PIECE_RADIUS = PIECE_DIAMETER_TO_SQUARE_SIZE_RATIO*min(SQUARE_WIDTH, SQUARE_HEIGHT)//2
MOVE_DOT_RADIUS = min(SQUARE_WIDTH, SQUARE_HEIGHT)//5

RED = (230, 50, 50)
WHITE = (255, 255, 255)
GRAY = (130, 130, 130)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 153)
GOLD = (255, 223, 0)
LIGHT_GREEN = (144, 238, 144)
PURPLE = (150, 0, 150)
LIGHT_PURPLE = (220, 50, 220)

CHECKERBOARD_BACKGROUND_COLOR = BLACK
CHECKERBOARD_SQUARES_COLOR = GRAY
PLAYER_TOP_COLOR = RED
PLAYER_BOTTOM_COLOR = BLUE
CROWN_COLOR = GOLD
HIGHLIGHT_COLOR = LIGHT_GREEN
MENU_BACKGROUND_COLOR = BLACK
GAME_OVER_MESSAGE_COLOR = (50, 210, 210)

BUTTON_BG_COLOR = PURPLE
BUTTON_BG_HIGHLIGHT_COLOR = LIGHT_PURPLE
BUTTON_TEXT_COLOR = WHITE
MENU_BUTTON_TEXT_SIZE = 128
MENU_TEXT_COLOR = GRAY
MENU_TEXT_SIZE = 42
