from checkers.game_constants import ROWS, COLUMNS

FPS = 60
WINDOW_WIDTH, WINDOW_HEIGHT = 1000, 1000
ICON_PATH = './img/checkers_logo.png'
WINDOW_CAPTION = 'Polish Checkers by Paweł Mędyk'


GAME_WINDOW_HORIZONTAL_OFFSET = 0
GAME_WINDOW_VERTICAL_OFFSET = 70
GAME_WINDOW_WIDTH = WINDOW_WIDTH - GAME_WINDOW_HORIZONTAL_OFFSET
GAME_WINDOW_HEIGHT = WINDOW_HEIGHT - GAME_WINDOW_VERTICAL_OFFSET

SQUARE_WIDTH = GAME_WINDOW_WIDTH//COLUMNS
SQUARE_HEIGHT = GAME_WINDOW_HEIGHT//ROWS

CROWN_IMG_PATH = './img/crown.png'
PIECE_DIAMETER_TO_SQUARE_SIZE_RATIO = 3/4
PIECE_RADIUS = PIECE_DIAMETER_TO_SQUARE_SIZE_RATIO*min(SQUARE_WIDTH, SQUARE_HEIGHT)//2
MOVE_DOT_RADIUS = min(SQUARE_WIDTH, SQUARE_HEIGHT)//5

PLAYER_TOP_COLOR_NAME = 'RED'
PLAYER_BOTTOM_COLOR_NAME = 'BLUE'

RED = (230, 50, 50)
WHITE = (255, 255, 255)
GRAY = (130, 130, 130)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 153)
GOLD = (255, 223, 0)
LIGHT_GREEN = (144, 238, 144)
PURPLE = (150, 0, 150)
LIGHT_PURPLE = (220, 50, 220)

CHECKERBOARD_BACKGROUND_COLOR = BLACK
CHECKERBOARD_SQUARES_COLOR = GRAY
PLAYER_TOP_COLOR = RED
PLAYER_BOTTOM_COLOR = BLUE
CROWN_COLOR = GOLD
HIGHLIGHT_COLOR = LIGHT_GREEN
PREVIOUS_PIECE_POSITION_COLOR = (159, 43, 104)
LAST_PERFORMED_SEQUENCE_COLOR = (242, 210, 189)
MENU_BACKGROUND_COLOR = BLACK
GAME_OVER_MESSAGE_COLOR = (200, 240, 200)
TURN_INFO_TEXT_SIZE = 42
TURN_INFO_TEXT_COLOR = WHITE
TURN_INFO_POS = (20, 20)

BUTTON_BG_COLOR = PURPLE
BUTTON_BG_HIGHLIGHT_COLOR = LIGHT_PURPLE
BUTTON_TEXT_COLOR = WHITE
MENU_BUTTON_TEXT_SIZE = 128
MENU_TEXT_COLOR = GRAY
MENU_TEXT_SIZE = 42
OPTIONS_TEXT_SIZE = 32