ROWS, COLUMNS = 10, 10
INITIAL_PIECE_COUNT = COLUMNS//2*(ROWS//2-1)

NON_CAPTURE_QUEEN_MOVES_COUNT_LIMIT = 25
MOVES_COUNT_FOR_1V3_ENDGAME = 16*2
MOVES_COUNT_FOR_1V2_ENDGAME = 5*2
MOVES_COUNT_FOR_1V1_ENDGAME = 1
BOARD_STATE_REPETITION_LIMIT = 3
